### ISSUE TITLE
predict() function

### ISSUE THREAD

**Issue by damirpolat** [UBod/apcluster#4]
Hey, 
I was wondering what the status of `predict()` function is. Are you going to add it in the near future? 
There is a StackOverflow [answer](https://stackoverflow.com/questions/34932692/using-the-apcluster-package-in-r-it-is-possible-to-score-unclustered-data-poi/37561336#37561336) that gives the basics of predict, but I don't know if there is more to it than that.

Regards, 
Damir

**Comment by UBod** [comment]
Sorry for the late reply! No, there is still no implementation of `predict()` along the lines of the StackOverflow answer you are quoting. Unfortunately, that would require some redesign and reimplementations of the pipeline, and so far nobody was able to invest the time and effort. So, for the time being, you still need to rely on the code snippet in the StackOverflow post.

**Comment by damirpolat** [comment]
Ok, thank you!
